<?xml version="1.0" encoding="utf-8"?><Database Name="ORMTest" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=ORMTest;Integrated Security=True" SettingsObjectName="OrmComparison.Properties.Settings" SettingsPropertyName="ORMTestConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.ExecuteNonQuery" Method="ExecuteNonQuery">
    <Parameter Name="OutputData" Parameter="outputData" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="IntData" Parameter="intData" Type="System.Int32" DbType="Int" />
    <Parameter Name="GuidData" Parameter="guidData" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="StringData" Parameter="stringData" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BoolData" Parameter="boolData" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DateData" Parameter="dateData" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetSingleRecord" Method="GetSingleRecord">
    <Parameter Name="IntData" Parameter="intData" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSingleRecordResult">
      <Column Name="IntData" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GuidData" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StringData" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BoolData" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateData" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllRecords" Method="GetAllRecords">
    <ElementType Name="GetAllRecordsResult">
      <Column Name="IntData" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GuidData" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StringData" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BoolData" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateData" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>